<?php
    $style_classes = array(
        'style1' => 'crtplst_productList_style1 crtplst_productList_list_20',
        'style2' => 'crtplst_productList_style2 crtplst_productList_style1 crtplst_productList_list_21',
        'style3' => 'crtplst_productList_style3 crtplst_productList_list_22',
        'style4' => 'crtplst_productList_style4 crtplst_productList_list_23',
        'style5' => 'crtplst_productList_style5 crtplst_productList_list_24',
        'style6' => 'crtplst_productList_style6 crtplst_productList_list_25',
        'style7' => 'crtplst_productList_style7 crtplst_productList_list_26',
        'style8' => 'crtplst_productList_style8 crtplst_productList_list_27',
        'style9' => 'crtplst_productList_style9 crtplst_productList_list_28',
        'style10' => 'crtplst_productList_style10 crtplst_productList_list_29',
        'style11' => 'crtplst_productList_style11 crtplst_productList_list_30',
        'style12' => 'crtplst_productList_style13 crtplst_productList_list_31',
        'style13' => 'crtplst_productList_list_32',
        'style14' => 'crtplst_productList_list_32 crtplst_productList_list_33',
        'style15' => 'crtplst_productList_list_32 crtplst_productList_list_34',
        'style16' => 'crtplst_productList_list_32 crtplst_productList_list_35',
        'style17' => 'crtplst_productList_list_32 crtplst_productList_list_36',
        'style18' => 'crtplst_productList_list_32 crtplst_productList_list_37',
        'style19' => 'crtplst_productList_list_32 crtplst_productList_list_38',
        'style20' => 'crtplst_productList_list_32 crtplst_productList_list_39',
        'style21' => 'crtplst_productList_list_32 crtplst_productList_list_40',
        'style22' => 'crtplst_productList_list_temp_22',
        'style23' => 'crtplst_productList_list_temp_23',
    );
    $style_extra_class = isset($style_classes[$crtplst_products_style]) ? $style_classes[$crtplst_products_style] : '';