<?php
/**
 * 
 * @admin ~~// this is the dashboard general tab
 * 
 */
if ( ! defined( 'ABSPATH' ) ) exit;
	echo '<div id="general" class="bwd-admin-setting-tab">';
	   echo '<div class="bwd-general-container bwd-grid">';
		   echo '<div class="bwd-col-xxl-7 bwd-col-xl-7">';
				echo '<div class="bwd-general-changelog-container">';
					echo '<div class="bwd-general-changlog-wrap">';
						$changelogWrap = class_exists( 'ProbwdelementorBundle' )?'free':'not-pro';
						echo '<div class="bwd-general-changlog-'.$changelogWrap.'">';
							echo '<div class="bwd-general-changlog-free-header">';
								echo '<h3>'.$generalTitles[0].'</h3>';
								echo '<button>Free</button>';
							echo '</div>';
							echo '<div class="bwd-general-changlog-free-content">';
								echo '<div class="bwd-general-changlog-free-item">';
									echo '<ul class="bwd-changlog-change">';
										$changelog_file = plugin_dir_path(__FILE__) . '../../CHANGELOG.txt';
										$last_modified = filemtime($changelog_file);
										echo '<li><h6>'.esc_html__('Changes On ',BWDEB_PLUGIN_TD).'<span class="bwd-changlog-change-date">' . date('F d, Y', $last_modified) . '</span></h6></li>';
										echo '<button class="bwd-changlog-change-version">v'.BWDEB_PLUGIN_V.'</button>';
										if (file_exists($changelog_file)) {
											$changelog_content = file_get_contents($changelog_file);
											echo '<div  class="bwd-changlog-change-item">';
											echo '<li>';
											echo nl2br(esc_html($changelog_content));
											echo '</li>';
											echo '</div>';
										} else {
											echo '<p style="text-align: center;">'.esc_html__('Changelog file not found.',BWDEB_PLUGIN_TD).'</p>';
										}
									echo '</ul>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
						if(class_exists( 'ProbwdelementorBundle' )):
						echo '<div class="bwd-center-border"></div>';
						echo '<div class="bwd-general-changlog-pro">';
							echo '<div class="bwd-general-changlog-pro-header">';
								echo '<h3>'.$generalTitles[0].'</h3>';
								echo '<button>Pro</button>';
							echo '</div>';
							echo '<div class="bwd-general-changlog-pro-content">';
								echo '<div class="bwd-general-changlog-pro-item">';
									echo '<ul class="bwd-changlog-change">';
										$file_path = plugin_dir_path(__FILE__) . '../../../bwd-elementor-addons-pro/changelog.txt';
										$last_modifiedPro = filemtime($changelog_file);
										echo '<li><h6>'.esc_html__('Changes On ',BWDEB_PLUGIN_TD).'<span class="bwd-changlog-change-date">' . date('F d, Y', $last_modifiedPro) . '</span></h6></li>';
										echo '<button class="bwd-changlog-change-version">v'.BWDEB_THE_PRO_SOFT_VERSION.'</button>';
										if (file_exists($file_path)) {
											$changelog_content = file_get_contents($file_path);
											echo '<div class="bwd-changlog-change-item">';
											echo '<li>';
											echo nl2br(esc_html($changelog_content));
											echo '</li>';
											echo '</div>';
										} else {
											echo '<p style="text-align: center;">'.esc_html__('Changelog file not found.',BWDEB_PLUGIN_TD).'</p>';
										}
									echo '</ul>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
						endif;
					echo '</div>';
				echo '</div>';
		   echo '</div>';
		   echo '<div class="bwd-col-xxl-5 bwd-col-xl-5">';
				echo '<div class="bwd-general-widgetsbar-container">';
					echo '<div class="bwd-general-widgetsbar-title">';
						echo '<h3>'.$generalTitles[1].'</h3>';
					echo '</div>';
					echo '<div class="bwd-general-widget-active-chart">';
						echo '<div class="bwd-canvas-chart">';
							echo '<canvas id="bwdCanvasChart"></canvas>';
						echo '</div>';
					echo '</div>';
				echo '</div>';
		   echo '</div>';
	   echo '</div>';
	   echo '<div class="bwd-general-whats-new-template-container bwd-grid">';
		   echo '<div class="bwd-col-xxl-6 bwd-col-xl-5">';
				echo '<div class="bwd-general-whats-new-template">';
					echo '<div class="bwd-general-whats-new-template-title">';
						echo '<h3>'.$generalTitles[2].'</h3>';
					echo '</div>';
					echo '<div class="bwd-whats-new-items">';
					foreach($whatsNew as $newAll => $getNew):
						echo '<div class="bwd-whats-new-item">';
							echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).$getNew['img']).'" alt="">';
							echo '<div class="bwd-content-new">';
								echo '<h5>'.$getNew['name'].'</h5>';
								echo '<span>'.$getNew['desc'].'</span>';
							echo '</div>';
						echo '</div>';
					endforeach;
					echo '</div>';
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-col-xxl-6 bwd-col-xl-7">';
				echo '<div class="bwd-general-whats-new-template">';
					echo '<div class="bwd-general-whats-new-template-title">';
						echo '<h3 class="bwd-new-template-title">'.$generalTitles[3].'</h3>';
					echo '</div>';
					echo '<div class="bwd-new-template-items">';
						echo '<div class="bwd-new-template-item">';
							echo '<img src="https://bwd-assets.netlify.app/templateOne.jpg" alt="Template Image">';
						echo '</div>';
						echo '<div class="bwd-new-template-item">';
							echo '<img src="https://bwd-assets.netlify.app/templateTwo.jpg" alt="Template Image">';
						echo '</div>';
						echo '<div class="bwd-new-template-item">';
							echo '<img src="https://bwd-assets.netlify.app/templateThree.jpg" alt="Template Image">';
						echo '</div>';
					echo '</div>';
					echo '<div class="bwd-view-new-template-button">';
						echo '<a target="_blank" href="https://bestwpdeveloper.com/templates/">'.esc_html__('Check All The Templates',BWDEB_PLUGIN_TD).'</a>';
				   echo '</div>';
				echo '</div>';
			echo '</div>';
	   echo '</div>';
	   echo '<div class="bwd-request-for-review-container bwd-grid">';
			echo '<div class="bwd-col-xxl-12">';
				echo '<div class="bwd-request-review-background">';
					echo '<div class="bwd-request-review-content">';
						echo '<h2>'.$generalTitles[4].'</h2>';
						echo '<span>'.esc_html__('We are continiously working to make "BWD Elementor Addons" better, everyday. Your kind feedback will surely encourage us to move forward with the development.',BWDEB_PLUGIN_TD).'</span>';
					echo '</div>';
					echo '<div class="bwd-request-review-button">';
						echo '<a target="_blank" href="https://wordpress.org/plugins/bwd-elementor-addons/#reviews">'.esc_html__('Request For Review',BWDEB_PLUGIN_TD).'</a>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
	   echo '</div>';

	   echo '<div class="bwd-system-requerment-container bwd-grid">';
			echo '<div class="bwd-col-xxl-3 bwd-col-xl-4">';
				echo '<div class="bwd-feature-request-wrap">';
					echo '<div class="bwd-feature-request-img">';
						echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/Feature.svg').'" alt="">';
					echo '</div>';
					echo '<div class="bwd-feature-request-content">';
						echo '<h3>'.$generalTitles[5].'</h3>';
						echo '<span>Please feel free to give any suggestions to include any features about BWD Elementor Addons for Elementor.</span>';
					echo '</div>';
					echo '<div class="bwd-feature-request-button">';
						echo '<a target="_blank" href=" https://bestwpdeveloper.com/request-a-feature">Request a Features</a>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-col-xxl-9 bwd-col-xl-8">';
				echo '<div class="bwd-system-requerment-wrap">';
					echo '<div class="bwd-system-requerment-title">';
						echo '<h3>'.$generalTitles[6].'</h3>';
					echo '</div>';
					echo '<div class="bwd-system-requerment-content">';
						echo '<div class="bwd-system-requerment-items">';
							echo '<div class="bwd-system-requerment-item">';
								echo '<div class="bwd-system-requerment-lable">';
									echo '<span>Plugin Required</span>';
								echo '</div>';
								echo '<div class="bwd-system-requerment-value">';
									echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/red-icon.svg').'" alt="">';
									echo '<span>Elementor</span>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-system-requerment-item">';
								echo '<div class="bwd-system-requerment-lable">';
									echo '<span>Minimum PHP v</span>';
								echo '</div>';
								echo '<div class="bwd-system-requerment-value">';
									echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/green-icon.svg').'" alt="">';
									echo '<span>v 7.0</span>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-system-requerment-item">';
								echo '<div class="bwd-system-requerment-lable">';
									echo '<span>Minimum Elementor v</span>';
								echo '</div>';
								echo '<div class="bwd-system-requerment-value">';
									echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/green-icon.svg').'" alt="">';
									echo '<span>v 3.0.0</span>';
								echo '</div>';
							echo '</div>';
						echo '</div>';
						echo '<div class="bwd-center-border"></div>';
						echo '<div class="bwd-system-requerment-items">';
							echo '<div class="bwd-system-requerment-item">';
								echo '<div class="bwd-system-requerment-lable">';
									echo '<span>WooCommerce Plugin</span>';
								echo '</div>';
								echo '<div class="bwd-system-requerment-value">';
									echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/red-icon.svg').'" alt="">';
									echo '<span>For e-commerce widgets</span>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-system-requerment-item">';
								echo '<div class="bwd-system-requerment-lable">';
									echo '<span>Max. Post Size</span>';
								echo '</div>';
								echo '<div class="bwd-system-requerment-value">';
									echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/green-icon.svg').'" alt="">';
									echo '<span>Currently: 8000M</span>';
								echo '</div>';
							echo '</div>';

							echo '<div class="bwd-system-requerment-item">';
								echo '<div class="bwd-system-requerment-lable">';
									echo '<span>WP Memory Limit</span>';
								echo '</div>';
								echo '<div class="bwd-system-requerment-value">';
									echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/red-icon.svg').'" alt="">';
									echo '<span>Currently: 40M (min: 265M)</span>';
								echo '</div>';
							echo '</div>';

						echo '</div>';
					echo '</div>';
					echo '<div class="bwd-system-requerment-notes">';
						echo '<span><span>Note:</span> If you have multuple addon so you need some more requerment some cases so make sure you added more memory for others addon too.</span>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
	   echo '</div>';
	   echo '<div class="bwd-general-footer-container bwd-grid">';
			echo '<div class="bwd-col-xxl-4 bwd-col-xl-4 bwd-col-lg-6">';
				echo '<div class="bwd-general-footer-item-wrap">';
					echo '<div class="bwd-general-footer-item-content">';
						echo '<h3>'.$generalTitles[7].'</h3>';
						echo '<span>The help documentation provides comprehensive guidance on installing, activating, and using the BWD Elementor Addons Bundle, ensuring a seamless experience for users.</span>';
					echo '</div>';
					echo '<div class="bwd-general-footer-item-image">';
						echo '<img src="https://bwd-assets.netlify.app/documentation.svg" alt="">';
					echo '</div>';
					echo '<div class="bwd-general-footer-item--button">';
						echo '<a target="_blank" href="https://bestwpdeveloper.com/documentation">documentation</a>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-col-xxl-4 bwd-col-xl-4 bwd-col-lg-6">';
				echo '<div class="bwd-general-footer-item-wrap">';
					echo '<div class="bwd-general-footer-item-content">';
						echo '<h3>'.$generalTitles[8].'</h3>';
						echo '<span>The reviews showcase the satisfaction of users with the BWD Elementor Addons Bundle, highlighting its ease of use, versatility, and effectiveness in enhancing websites.</span>';
					echo '</div>';
					echo '<div class="bwd-general-footer-item-image">';
						echo '<img src="https://bwd-assets.netlify.app/customer-review-request.svg" alt="">';
					echo '</div>';
					echo '<div class="bwd-general-footer-item--button">';
						echo '<a target="_blank" href="https://wordpress.org/plugins/bwd-elementor-addons/#reviews">Show your Love</a>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-col-xxl-4 bwd-col-xl-4 bwd-col-lg-6">';
				echo '<div class="bwd-general-footer-item-wrap">';
					echo '<div class="bwd-general-footer-item-content">';
						echo '<h3>'.$generalTitles[9].'</h3>';
						echo '<span>The support system ensures users receive timely assistance and resolution of any queries or issues encountered while using the BWD Elementor Addons Bundle.</span>';
					echo '</div>';
					echo '<div class="bwd-general-footer-item-image">';
						echo '<img src="https://bwd-assets.netlify.app/support.svg" alt="">';
					echo '</div>';
					echo '<div class="bwd-general-footer-item--button">';
						$supportCheck = !class_exists( 'ProbwdelementorBundle' )?'https://wordpress.org/support/plugin/bwd-elementor-addons/':'https://bestwpdeveloper.com/support/';
						echo '<a target="_blank" href="'.$supportCheck.'">Get Support</a>';
					echo '</div>';
				echo '</div>';
			echo '</div>';
	   echo '</div>';
	echo '</div>';
// End general tab 